#index:
#    path: /
#    controller: App\Controller\DefaultController::index


home:
    path: /
    controller: App\Controller\HomeController::index
    methods: [GET,POST]
query:
    path: /query
    controller: App\Controller\TourController::queryBuilder