#index:
#    path: /
#    controller: App\Controller\DefaultController::index


home:
    path: /
    controller: App\Controller\HomeController::index
    methods: [GET,POST]

# config/routes.yaml
login:
    path:       /login
    controller: App\Controller\SecurityController::login
    methods: POST